language: cpp

compiler:
  - gcc

addons:
  apt:
    packages: libboost-all-dev

install:
  - export PATH="$HOME/.cargo/bin:$PATH"
  - cmake .
  - make deps

before_script:
  # cmake was already run

script:
  # Build
  - make
  # The project uses ctest. Let's enable this later
  - make test
