language: cpp

compiler:
  - gcc

addons:
  apt:
    packages: libboost-all-dev

before_script:
  # run cmake
  - cmake .

script:
  # Build
  - make
  # The project uses ctest. Let's enable this later
  #- make test
